name: ci

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.node-version }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x, 20.x, 22.x]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - if: runner.os == 'Windows'
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.symlinks true
      - uses: actions/checkout@v4
        with:
          show-progress: false
      - name: v${{ matrix.node-version }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm test
